{{- if .Values.global.localpathEnable }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "local-path-provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.defaultSettings.registrySecret }}
  - name: {{ .Values.defaultSettings.registrySecret }}
{{- end }}
{{- end }}
{{- end -}}
